pacman:
  - ansible
  - aria2
  - bat
  - btop
  - chezmoi
  - csvlens
  - ddcutil
  - difftastic
  - direnv
  - dmidecode
  - duf
  - eza
  - fastfetch
  - fd
  - fio
  - fzf
  - gdu
  - geoipupdate
  - git
  - git-cliff
  - github-cli
  - glow
  - go-yq
  - gping
  - gum
  - helix
  - htop
  - httpie
  - hyperfine
  - imagemagick
  - jless
  - just
  - lnav
  - lshw
  - markdownlint-cli
  - miniserve
  - nmap
  - ouch
  - pacutils
  - pandoc-cli
  - parallel
  - pnpm
  - pre-commit
  - pueue
  - rbw
  - rclone
  - restic
  - ripgrep
  - rsync
  - rustscan
  - sd
  - speedtest-cli
  - sshfs
  - starship
  - taplo-cli
  - tealdeer
  - tokei
  - trash-cli
  - usbutils
  - vhs
  - xh
  - yazi
  - zoxide

npm:
  - "@bitwarden/cli"
  - gh-pages
  - prettier
  - repomix
