# -*- mode: toml; -*-

["{{ .dirs.rel.external }}/codex-meter@slobbe.github.io.zip"]
refreshPeriod = "168h"
type = "file"
url = '{{ (gitHubLatestReleaseAssetURL "slobbe/codex-meter" "codex-meter@slobbe.github.io-*.zip") }}'
