[".local/share/fonts/SegoeUI"]
exact = true
format = "zip"
refreshPeriod = "168h"
type = "archive"
url = "https://aka.ms/segoeuifont"

[".local/share/fonts/SegoeUIVariable"]
exact = true
format = "zip"
refreshPeriod = "168h"
type = "archive"
url = "https://aka.ms/SegoeUIVariable"

[".local/share/fonts/TwemojiFlags.ttf"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/fonts/releases/download/TwemojiFlags/TwemojiFlags.ttf"

["{{ .external_dir_relative }}/win11-fonts.zip"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/fonts/releases/download/Win11/Win11-Chinese_Simplified.zip"
