arch:
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - otf-latinmodern-math
  - otf-monaspace-nerd
  - ttf-cascadia-code-nerd
  - ttf-maplemononormal-nf-cn-unhinted
  - ttf-mona-sans
  # TODO: ttf-ms-win11-auto does not work for me. I have to use a separate
  # script to install Microsoft fonts.
  # - ttf-ms-win11-auto
  # - ttf-ms-win11-auto-zh_cn
  - ttf-twemoji
