pacman:
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - noto-fonts-extra
  - otf-latinmodern-math
  - otf-monaspace-nerd
  - ttf-cascadia-code-nerd
  - ttf-mona-sans
  - ttf-ms-win11-auto
  - ttf-ms-win11-auto-zh_cn
  - ttf-twemoji
