#!/bin/bash
# -*- mode: sh; -*-
set -o errexit
set -o nounset
set -o pipefail

source "$CHEZMOI_SOURCE_DIR/.snippets/has-nvidia.sh"

if has-nvidia; then
  yq eval '.modules.nvidia_smi = true' '/usr/lib/netdata/conf.d/go.d.conf' --input-format yaml --output-format yaml
else
  cat '/usr/lib/netdata/conf.d/go.d.conf'
fi
