#!/bin/bash
# https://github.com/gokcehan/lf/wiki/Previews#with-kitty-and-pistol

file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$(file -Lb --mime-type "$file")" =~ ^image ]]; then
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
  exit 1
fi

bat --force-colorization "$file"
