flatpak:
  - com.github.tchx84.Flatseal
  - com.tencent.WeChat
  - com.tencent.wemeet
  - io.typora.Typora
  - moe.tsuna.tsukimi
  - net.meshlab.MeshLab # `aur/meshlab-appimage` does not support dark mode
  - org.paraview.ParaView # `extra/paraview` does not support dark mode

pacman:
  # ----------------------- Hardware Video Acceleration ---------------------- #
  # ref: <https://wiki.archlinux.org/title/Hardware_video_acceleration#Verification>
  - libva-utils # VA-API
  - mpv
  - vdpauinfo # VDPAU
  - vulkan-tools # Vulkan

  # ------------------------------ Applications ------------------------------ #
  - 3dslicer
  - blender
  - drawio-desktop
  - flameshot
  - gimp
  - haruna
  - inkscape
  - kitty
  - microsoft-edge-stable-bin
  - obs-studio
  - obsidian
  - pot-translation
  - qalculate-gtk
  - remmina
  - telegram-desktop
  - visual-studio-code-bin
  - vlc
  - wps-office-365
  - wps-office-365-fonts
  - zotero

  # optional for: pot-translation, Stirling PDF
  - tesseract-data-chi_sim
  - tesseract-data-eng
