words:
  - adwaita
  - archlinuxcn
  - biber
  - bioconda
  - bmalehorn
  - ccmp
  - chouzz
  - chrony
  - chsh
  - clangd
  - cockroachdb
  - cronie
  - czrc
  - dasel
  - ddns
  - dhclient
  - dhcpd
  - direnvrc
  - dnsmasq
  - eamodio
  - expt
  - fluentd
  - gcampax
  - gcan
  - gfxmode
  - gfxpayload
  - glfw
  - gloga
  - goauthing
  - gomod
  - gpasswd
  - gping
  - groh
  - gruntfuggly
  - gsettings
  - gvfs
  - hdfs
  - ibus
  - icat
  - kubeproxy
  - liblaf
  - libva
  - libvdpau
  - lighttpd
  - lusiadas
  - menpo
  - miniconda
  - mkinitcpio
  - mschapv
  - nginxplus
  - nginxvts
  - nouseask
  - nvarner
  - nvitop
  - nvme
  - paperwm
  - peap
  - pflannery
  - pgbouncer
  - pihole
  - powerd
  - qbittorrent
  - rclone
  - recursor
  - setaf
  - simpleitk
  - tamasfe
  - tela
  - tengine
  - tldr
  - tokei
  - toolsai
  - traefik
  - typst
  - udisks
  - ungrabbed
  - usernamehw
  - vcsa
  - vdpau
  - vdpauinfo
  - vernemq
  - vscodeintellicode
  - vuetorrent
  - wemeet
  - yzhang
  - zotero
  - zoxide
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - fonts
  - fullstack
  - k8s
  - makefile
  - npm
  - php
  - python
  - python-common
  - r
allowCompoundWords: true
