# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json

# ref: <https://docs.linuxserver.io/images/docker-qbittorrent/>
# ref: <https://github.com/VueTorrent/VueTorrent/wiki/Installation>

services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      # DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
      PGID: 33565
      PUID: 20811
      TORRENTING_PORT: 63722
      UMASK: "002"
      WEBUI_PORT: 8080
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - 63722:63722/tcp
      - 63722:63722/udp
      - 8080:8080
    pull_policy: weekly
    restart: unless-stopped
    volumes:
      - ./config:/config
      - type: bind
        source: /mnt/PC07sda1/srv/qbittorrent/downloads
        target: /downloads
        bind:
          create_host_path: false

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.208.11.0/24
          gateway: 10.208.11.1
        - subnet: fd45:6e65:685e::/64
          gateway: fd45:6e65:685e::1
