[".config/fastfetch/config.jsonc"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/fastfetch-cli/fastfetch/raw/dev/presets/examples/10.jsonc"

[".local/bin/fTetWild"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/pkg/releases/download/fTetWild/fTetWild-X64-Linux"
