# -*- mode: ini; -*-
# ref: <file:///usr/lib/netdata/conf.d/netdata.conf>

# netdata configuration
#
# You can get the latest version of this file, using:
#
#  netdatacli dumpconfig > /etc/netdata/netdata.conf
#
# You can also download it using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#

[plugins]
# These plugins consumes 100% CPU from time to time, so we disable them.
cups = no
freeipmi = no
