[".config/fastfetch/config.jsonc"]
refreshPeriod = "168h"
type = "file"
urls = [
  "file:///usr/share/fastfetch/presets/examples/10.jsonc",
  "https://cdn.jsdelivr.net/gh/fastfetch-cli/fastfetch/presets/examples/10.jsonc",
]
