# -*- mode: ini; -*-
# ref: <https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/pacman/pacman.conf>
# ref: <https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/pacman.conf>
# ref: <https://man.archlinux.org/man/pacman.conf.5>

[options]
HoldPkg = glibc pacman
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 8
DownloadUser = alpm
ILoveCandy

# ref: <https://man.archlinux.org/man/pacman.conf.5>
# ! The order of repositories in the configuration files matters; repositories listed first will take precedence over those listed later in the file when packages in two repositories have identical names, regardless of version number.
# ---------------------------------- CachyOS --------------------------------- #

[cachyos-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-core-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-extra-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

# -------------------------------- Arch Linux -------------------------------- #

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# ---------------------------- Custom Repositories --------------------------- #

[archlinuxcn]
Include = /etc/pacman.d/archlinuxcn-mirrorlist

[arch4edu]
Include = /etc/pacman.d/arch4edu-mirrorlist

# [bioarchlinux]
# Include = /etc/pacman.d/bioarchlinux-mirrorlist

[orhun]
Server = https://pkgbuild.com/~orhun/repo
