#:schema https://developers.openai.com/codex/config-schema.json
# ref: <https://learn.chatgpt.com/docs/config-file/config-sample>

approvals_reviewer = "auto_review"
sandbox_mode = "workspace-write"

[analytics]
enabled = false

[features]
memories = true

[feedback]
enabled = false

[sandbox_workspace_write]
network_access = true
writable_roots = [
  # ref: <https://github.com/openai/codex/issues/3141#issuecomment-4236522565>
  "/dev/dri",
  "/dev/nvidia",
  "~/.bun",
  "~/.cache",
  "~/.cargo",
  "~/.config",
  "~/.npm",
  "~/.pixi"
]

[shell_environment_policy.set]
UV_FROZEN = "1"
