# ref: <https://github.com/noborus/ov/blob/master/ov.yaml>
# ref: <https://github.com/noborus/ov/blob/master/oviewer/config.go>

Mode:
  bat:
    Header: 3
    WrapMode: false
  git-diff:
    SectionDelimiter: ^diff --git a/|--- \w+$
  git-log:
    Header: 3
    SectionDelimiter: ^commit \w{40}$
  git-show:
    Header: 3
  man:
    SectionDelimiter: ^[^\s]

# ref: <https://noborus.github.io/ov/man/index.html>
StyleOverStrike:
  Foreground: aqua
  Bold: true
StyleOverLine:
  Foreground: red
  Underline: true
