"$schema" = "https://starship.rs/config-schema.json"

[battery]
disabled = true

[c]
format = '\[[$symbol( ($name-)$version)]($style)\]'
version_format = "$raw"
symbol = "" # nf-custom-c
detect_extensions = [
  "c",
  "C",
  "c++",
  "cc",
  "cpp",
  "cxx",
  "h",
  "H",
  "h++",
  "hpp",
  "hxx",
]
detect_files = ["CMakeCache.txt", "CMakeLists.txt"]
commands = [["clang", "--version"], ["gcc", "--version"], ["cc", "--version"]]

[character]
success_symbol = "[>](bold green)"
error_symbol = "[](bold red)"     # nf-fa-close

[cmake]
format = '\[[$symbol($version)]($style)\]'
version_format = "$raw"

[cmd_duration]
format = '\[[󱎫 $duration]($style)\]' # nf-md-timer

[conda]
format = '\[[$symbol $environment]($style)\]'
symbol = ""                                  # nf-fa-circle_o

[directory]
read_only = " 󰌾" # nf-md-lock

[git_branch]
format = '\[[$symbol $branch]($style)\]'
symbol = ""                             # nf-oct-git_branch

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\])'
ahead = ""                                         # nf-fa-up_long
behind = ""                                        # nf-fa-down_long
diverged = ""                                      # nf-fa-up_down
renamed = ""                                       # nf-fa-angles_right
deleted = ""                                       # nf-fa-close

[git_metrics]
disabled = false
format = '(\[([+$added]($added_style))([-$deleted]($deleted_style))\])'

[golang]
format = '\[[$symbol( $version)]($style)\]'
version_format = "$raw"
symbol = "󰟓"                                # nf-md-language_go

[hostname]
format = "@[$ssh_symbol$hostname]($style) "
ssh_symbol = ""

[java]
format = '\[[$symbol( $version)]($style)\]'
version_format = "$raw"
symbol = "󰬷"                                #  nf-md-language_java

[lua]
format = '\[[$symbol( $version)]($style)\]'
version_format = "$raw"
symbol = "󰢱"                                # nf-md-language_lua

[memory_usage]
threshold = 0
format = '\[$symbol [$ram]($style)\]'
symbol = "󰍛"                          # nf-md-memory
disabled = false

[nodejs]
format = '\[[$symbol( $version)]($style)\]'
version_format = "$raw"
symbol = "󰎙"                                # nf-md-nodejs

[package]
format = '\[[$symbol $version]($style)\]'
version_format = "$raw"
symbol = ""                              # nf-oct-package

[python]
format = '\[[$symbol $pyenv_prefix($version)(\($virtualenv\))]($style)\]'
version_format = "$raw"
symbol = "󰌠"                                                              # nf-md-language_python

[rust]
format = '\[[$symbol( $version)]($style)\]'
version_format = "$raw"
symbol = "󱘗"                                # nf-md-language_rust

[status]
symbol = ""                                           # nf-fa-close
not_executable_symbol = " "                           # nf-fa-ban
not_found_symbol = " "                                # nf-fa-search
sigint_symbol = "!"
signal_symbol = ""                                    # nf-fa-bolt
map_symbol = true
pipestatus = true
pipestatus_segment_format = "[$symbol$status]($style)"
disabled = false

[username]
format = "[$user]($style)"

[custom.bitwarden]
when = 'test -n "$BW_SESSION"'
shell = "sh"
symbol = "󰞀"                            # nf-md-shield_half_full
format = '\[[$symbol unlock]($style)\]'

[custom.proxy]
command = "gfw now --color=always"
when = 'test -n "$https_proxy"'
shell = "sh"
symbol = "󰖟"                       # nf-md-web
style = ""
format = '\[[$output]($style)\]'
