["srv/jellyfin/fonts/fallback/NotoSansCJKjp-Medium.woff2"]
path = "NotoSansCJKjp-hinted-standard/NotoSansCJKjp-Medium.woff2"
refreshPeriod = "168h"
type = "archive-file"
url = "https://raw.githubusercontent.com/CodePlayer/webfont-noto/refs/heads/master/release/NotoSansCJKjp-hinted-standard.zip"

["srv/jellyfin/fonts/fallback/NotoSansCJKsc-Medium.woff2"]
path = "NotoSansCJKsc-hinted-standard/NotoSansCJKsc-Medium.woff2"
refreshPeriod = "168h"
type = "archive-file"
url = "https://raw.githubusercontent.com/CodePlayer/webfont-noto/refs/heads/master/release/NotoSansCJKsc-hinted-standard.zip"

["srv/jellyfin/fonts/system/NotoSansCJK-VF.otf.ttc"]
refreshPeriod = "168h"
type = "file"
url = "https://raw.githubusercontent.com/notofonts/noto-cjk/refs/heads/main/Sans/Variable/OTC/NotoSansCJK-VF.otf.ttc"
