# -*- mode: dotenv; -*-
# ref: <file:///etc/journalctl-desktop-notification.conf>
# ref: <https://gitlab.com/Zesko/journalctl-desktop-notification>

### Ignore annoying spam messages
ERROR_FILTER='dolphin|sudo:auth|error: kex_exchange_identification: read: Connection reset by peer'

### Set a custom terminal app and its argument e.g. "konsole -e" for the KDE default terminal or "gnome-terminal -- bash -c" for the GNOME default terminal.
TERMINAL='ghostty'
TERMINAL_ARG='--gtk-titlebar-hide-when-maximized=false -e'
