"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode = "mtime"

[opener]
code = [{ run = 'code "$@"', orphan = true, desc = "code", for = "unix" }]
extract = [{ run = 'ouch decompress "$@"', desc = "Extract", for = "unix" }]
open = [
  { run = 'xdg-open "$1" &> /dev/null', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
view = [
  { run = '${VIEWER:-bat} "$@"', desc = "$VIEWER", block = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "model/*", use = [
    "open",
    "reveal",
  ] },
  { mime = "text/*", use = [
    "edit",
    "code",
    "open",
    "reveal",
    "view",
  ] },
]
