#:schema https://starship.rs/config-schema.json
"$schema" = "https://starship.rs/config-schema.json"

[custom.remote]
command = 'basename -- "$(findmnt --noheadings --output TARGET --target "$PWD")"'
format = '\[[$symbol($output)]($style)\]'
shell = "sh"
symbol = "󰡰 "
when = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true
