arch:
  - journalctl-desktop-notification
  - xdg-terminal-exec

  # hardware video acceleration
  - libva-utils # VA-API
  - mpv
  - vdpauinfo # VDPAU
  - vulkan-tools # Vulkan

  # applications
  #TODO: archlinuxcn/3dslicer is broken. switch to that once it's fixed
  - 3dslicer-bin
  - blender
  - drawio-desktop
  - gimp
  - haruna
  - inkscape
  - microsoft-edge-stable-bin
  - mission-center
  - obs-studio
  - obsidian
  - paraview
  - qalculate-gtk
  - remmina
  - telegram-desktop
  - visual-studio-code-bin
  - vlc
  - vlc-plugins-all
  - wl-clipboard
  - wps-office-365
  - wps-office-365-fonts

flatpak:
  - com.github.tchx84.Flatseal
  - com.tencent.WeChat
  - com.tencent.wemeet
  - moe.tsuna.tsukimi
