# ref: <https://yazi-rs.github.io/docs/configuration/yazi>

[mgr]
linemode = "mtime"

[[opener.code]]
run = 'code "$@"'
orphan = true
desc = "code"
for = "unix"

[[opener.extract]]
run = 'ouch decompress "$@"'
desc = "Extract"
for = "unix"

[[opener.open]]
run = 'xdg-open "$@" &> /dev/null'
orphan = true
desc = "Open"
for = "linux"

[[opener.view]]
run = '${VIEWER:-bat} "$@"'
block = true
desc = "$VIEWER"
for = "unix"

[[open.prepend_rules]]
mime = "model/*"
use = ["open", "reveal"]

[[open.prepend_rules]]
mime = "text/*"
use = ["code", "edit", "open", "reveal", "view"]
