# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json

name: Caddy

services:
  caddy:
    cap_add:
      - NET_ADMIN
    container_name: caddy
    env_file:
      - ./vars.env
    image: caddybuilds/caddy-cloudflare:alpine
    network_mode: host # I'm too lazy to configure IPv6
    pull_policy: weekly
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-config:/config
      - caddy-data:/data

volumes:
  caddy-config:
  caddy-data:
