[".local/bin/utils"]
executable = true
type = "file"
url = "https://github.com/liblaf/utils.py/releases/latest/download/utils-linux-x64"

[".local/chezmoi/alist"]
type = "archive"
url = "https://github.com/alist-org/alist/releases/latest/download/alist-linux-amd64.tar.gz"
