set allow-duplicate-variables := true
set dotenv-load := true

import "justfiles/arch.just"
import "justfiles/assets.just"
import "justfiles/config.just"
import "justfiles/sing-box.just"
import "justfiles/ventoy.just"
import "justfiles/windows.just"

default: arch assets sing-box windows
