version: "3"

includes:
  arch:
    taskfile: task/arch.yaml
  live-injection:
    taskfile: task/live-injection.yaml
  sing-box:
    taskfile: task/sing-box.yaml
  ubuntu:
    taskfile: task/ubuntu.yaml
  ventoy:
    taskfile: task/ventoy.yaml

tasks:
  default:
    deps:
      - arch
      - live-injection
      - sing-box
      - ubuntu
      - ventoy
