[".local/bin/fTetWild"]
executable = true
path = "bin/FloatTetwild_bin"
refreshPeriod = "168h"
type = "archive-file"
url = "https://github.com/chrismile/fTetWild/releases/latest/download/fTetWild-v0.1.0-x86_64-linux.zip"
