connShowProcess: true
hideAfterStartup: true
hideTrayIcon: false
proxyOrder: 1
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
showNewVersionIcon: true
showTrayProxyDelayIndicator: true
systemTheme: true
trayOrders:
  - - icon
  - - status
    - traffic
    - text

profileParsersText: |-
  parsers:
    - reg: sub.nysubs.xyz
      file: /home/liblaf/.config/clash/parser.js
