#:schema https://yazi-rs.github.io/schemas/keymap.json

# ref: <https://github.com/yazi-rs/plugins/tree/main/chmod.yazi>
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# ref: <https://github.com/yazi-rs/plugins/tree/main/mount.yazi>
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

# ref: <https://github.com/yazi-rs/plugins/tree/main/zoom.yazi>
[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

# ref: <https://github.com/yazi-rs/plugins/tree/main/zoom.yazi>
[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"
