# ref: <https://help.mirrors.cernet.edu.cn/anaconda/>
# ref: <https://help.mirrors.cernet.edu.cn/anaconda-extra/>

[anaconda]
channels = [
  "atztogo",
  "auto",
  "biobakery",
  "bioconda",
  "c4aarch64",
  "caffe2",
  "conda-forge",
  "deepmodeling",
  "dglteam",
  "fastai",
  "fermi",
  "idaholab",
  "intel",
  "matsci",
  "menpo",
  "MindSpore",
  "mordred-descriptor",
  "msys2",
  "numba",
  "ohmeta",
  "omnia",
  "Paddle",
  "peterjc123",
  "plotly",
  "psi4",
  "pytorch-lts",
  "pytorch-test",
  "pytorch",
  "pytorch3d",
  "pyviz",
  "qiime2",
  "rapidsai",
  "rdkit",
  "simpleitk",
  "soumith",
  "stackless",
  "ursky",
  "viscid-hub",
]

[anaconda_extra]
channels = ["nvidia"]
