[".local/bin/chezmoi"]
executable = true
type = "file"
url = "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-linux-amd64"

[".local/bin/starship"]
type = "archive"
url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"

[".local/chezmoi/oh-my-zsh"]
type = "git-repo"
url = "https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git"

[".oh-my-zsh/custom/plugins/conda-zsh-completion"]
type = "git-repo"
url = "https://github.com/conda-incubator/conda-zsh-completion.git"

[".oh-my-zsh/custom/plugins/wakatime"]
type = "git-repo"
url = "https://github.com/sobolevn/wakatime-zsh-plugin.git"

[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
type = "git-repo"
url = "https://github.com/marlonrichert/zsh-autocomplete.git"

[".oh-my-zsh/custom/plugins/zsh-bitwarden"]
type = "git-repo"
url = "https://github.com/Game4Move78/zsh-bitwarden.git"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
