# ref: <https://copier.readthedocs.io/en/stable/settings/>

defaults:
  author_name: liblaf
  author_email: git@liblaf.me
  github_user: liblaf
  gitlab_user: liblaf

trust:
  - ~/Projects/liblaf/
  - gh:liblaf/
