# ref: <https://direnv.net/man/direnv.toml.1.html>

[global]
load_dotenv = true
strict_env = true
warn_timeout = "0s"

[whitelist]
exact = ["~/mnt/"]
prefix = ["~/.local/share/chezmoi/", "~/github/liblaf/", "~/playground/"]
