"$schema" = 'https://starship.rs/config-schema.json'

[c]
commands = [["clang", "--version"], ["gcc", "--version"], ["cc", "--version"]]
format = '\[[$symbol( ($name-)$version)]($style)\]'
symbol = "\ue61e"
version_format = "${raw}"

[cmd_duration]
format = "\\[[\U000f13ab $duration]($style)\\]"

[conda]
format = '\[[${symbol} ${environment}](${style})\]'
symbol = "\uf10c"

[custom.bitwarden]
description = "Bitwarden"
format = '\[[${symbol} Bitwarden](${style})\]'
symbol = "\uf132"
when = 'test -n "${BW_SESSION}"'

[custom.proxy]
command = "echo ${ALL_PROXY} | sed -e 's@^.*://@@' -e 's@/$@@g'"
description = "proxy"
format = '\[[$symbol $output]($style)\]'
symbol = "\ueb01"
when = 'test -n "${ALL_PROXY}"'

[custom.warp]
command = "echo WARP"
description = "warp"
format = '\[[$symbol $output]($style)\]'
symbol = "\uf0c2"
when = "warp-cli status | grep Connected"

[directory]
read_only = " \uf023"

[docker_context]
format = '\[[$symbol $context]($style)\]'
symbol = "\U000f0868"

[git_branch]
format = '\[[$symbol $branch]($style)\]'
symbol = "\ue725"

[git_metrics]
disabled = false
format = '\[[+$added]($added_style)[-$deleted]($deleted_style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol( $version)]($style)\]'
symbol = "\ue627"
version_format = "${raw}"

[java]
format = '\[[$symbol( $version)]($style)\]'
symbol = "\ue738"
version_format = "${raw}"

[memory_usage]
disabled = false
format = '\[$symbol [$ram]($style)\]'
symbol = "\U000f035b"
threshold = 0

[nodejs]
format = '\[[$symbol( $version)]($style)\]'
symbol = "\U000f0399"
version_format = "${raw}"

[package]
format = '\[[$symbol $version]($style)\]'
symbol = "\ueb29"
version_format = "${raw}"

[python]
format = '\[[${symbol} ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "\U000f0320"
version_format = "${raw}"

[rust]
format = '\[[$symbol( $version)]($style)\]'
symbol = "\U000f1617"
version_format = "${raw}"

[status]
disabled = false
format = '[$symbol $status]($style) '
symbol = "\uf00d"

[sudo]
disabled = false
format = '\[[$symbol sudo]($style)\]'
symbol = "\U000f0a8b"
