[".config/latexindent/latexindent.yaml"]
type = "file"
url = "https://github.com/liblaf/ilatex/raw/main/.latexindent.yaml"

[".config/lf/colors"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/colors.example"

[".config/lf/icons"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/icons.example"

[".local/bin/ddns"]
executable = true
type = "file"
url = "https://github.com/liblaf/ddns/releases/latest/download/ddns-x86_64-unknown-linux-gnu"

[".local/bin/reserves-lib-tsinghua-downloader"]
executable = true
path = "downloader"
type = "archive-file"
url = "https://github.com/libthu/reserves-lib-tsinghua-downloader/releases/latest/download/downloader-ubuntu-latest-py3.9.zip"

[".local/chezmoi/grub2-themes"]
stripComponents = 1
type = "archive"
url = "https://github.com/vinceliuice/grub2-themes/archive/refs/heads/master.tar.gz"

[".oh-my-zsh"]
stripComponents = 1
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/conda-zsh-completion"]
stripComponents = 1
type = "archive"
url = "https://github.com/conda-incubator/conda-zsh-completion/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
stripComponents = 1
type = "archive"
url = "https://github.com/marlonrichert/zsh-autocomplete/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-bitwarden"]
stripComponents = 1
type = "archive"
url = "https://github.com/Game4Move78/zsh-bitwarden/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-completions"]
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/heads/master.tar.gz"
