[".cache/dotfiles/dict.txt"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/broly8/libpinyin-dict/raw/master/dict.txt"

[".cache/dotfiles/grub2-themes"]
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/vinceliuice/grub2-themes/archive/refs/heads/master.tar.gz"

[".config/fastfetch/config.jsonc"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/fastfetch-cli/fastfetch/raw/dev/presets/examples/10.jsonc"

[".config/latexindent/latexindent.yaml"]
refreshPeriod = "168h"
type = "file"
url = "https://raw.githubusercontent.com/liblaf/ilatex/main/.latexindent.yaml"

[".config/ruff/.ruff.toml"]
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/copier-python/raw/refs/heads/main/template/.github/linters/.ruff.toml"

[".local/bin/bws"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/claps/releases/download/dev/bws-x86_64-unknown-linux-gnu"

[".local/bin/cf"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/rust-cli/releases/download/dev/cf-x86_64-unknown-linux-gnu"

[".local/bin/dlc"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/pkg/releases/download/domain-list-community/dlc-linux-amd64"

[".local/bin/fTetWild"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/pkg/releases/download/fTetWild/fTetWild-X64-Linux"

[".local/bin/geo"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/MetaCubeX/geo/releases/latest/download/geo-linux-amd64"

[".local/bin/getoptions"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/ko1nksm/getoptions/releases/latest/download/getoptions"

[".local/bin/gfw"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/rust-cli/releases/download/dev/gfw-x86_64-unknown-linux-gnu"

[".local/bin/pch"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/pre-commit-hooks/releases/download/dev/pch-x86_64-unknown-linux-gnu"

[".local/bin/pic"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/claps/releases/download/dev/pic-x86_64-unknown-linux-gnu"

[".local/bin/reserves-lib-tsinghua-downloader"]
executable = true
path = "downloader"
refreshPeriod = "168h"
type = "archive-file"
url = "https://github.com/libthu/reserves-lib-tsinghua-downloader/releases/latest/download/downloader-ubuntu-latest-py3.9.zip"

[".local/share/fonts/Win11"]
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/liblaf/win-fonts/releases/download/Win11/Win11-Chinese_Simplified.zip"
