[".config/fish/functions/fisher.fish"]
type = "file"
url = "https://github.com/jorgebucaran/fisher/raw/main/functions/fisher.fish"

[".config/fish/pkg/zoxide/init.fish"]
type = "file"
url = "https://github.com/ajeetdsouza/zoxide/raw/main/init.fish"

[".config/latexindent/latexindent.yaml"]
type = "file"
url = "https://github.com/liblaf/ilatex/raw/main/.latexindent.yaml"

[".config/lf/colors"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/colors.example"

[".config/lf/icons"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/icons.example"

[".local/bin/ddns-cli"]
executable = true
type = "file"
url = "https://github.com/liblaf/ddns-cli/releases/latest/download/ddns-cli-x86_64-unknown-linux-gnu"

[".local/bin/reserves-lib-tsinghua-downloader"]
executable = true
path = "downloader"
type = "archive-file"
url = "https://github.com/libthu/reserves-lib-tsinghua-downloader/releases/latest/download/downloader-ubuntu-latest-py3.9.zip"

[".local/bin/sing-box-cli"]
executable = true
type = "file"
url = "https://github.com/liblaf/sing-box-cli/releases/latest/download/sing-box-cli-x86_64-unknown-linux-gnu"

[".local/chezmoi/grub2-themes"]
stripComponents = 1
type = "archive"
url = "https://github.com/vinceliuice/grub2-themes/archive/refs/heads/master.tar.gz"

[".local/chezmoi/night.xpi"]
type = "file"
url = "https://github.com/tefkah/zotero-night/releases/latest/download/night.xpi"
