[mirrors]
anaconda = "https://mirrors.cernet.edu.cn/anaconda"
anaconda_extra = "https://mirrors.cernet.edu.cn/anaconda-extra"
arch4edu = "https://mirrors.cernet.edu.cn/arch4edu"
archlinux = "https://mirrors.cernet.edu.cn/archlinux"
archlinuxcn = "https://mirrors.cernet.edu.cn/archlinuxcn"
bioarchlinux = "https://mirrors.cernet.edu.cn/bioarchlinux"
cachyos = "https://mirrors.cernet.edu.cn/cachyos"
crates_io_index = "sparse+https://mirrors.cernet.edu.cn/crates.io-index"
dockerhub = "https://docker.m.daocloud.io"
flathub = "https://mirrors.cernet.edu.cn/flathub"
ghcr = "ghcr.nju.edu.cn"
go = "https://mirrors.huaweicloud.com/goproxy"  # CERNET 只有缓存
golang = "https://mirrorr.cernet.edu.cn/golang"
nodejs_release = "https://mirrors.cernet.edu.cn/nodejs-release"
npm = "https://mirrors.huaweicloud.com/repository/npm"  # CERNET 只有缓存
ntp = "ntp.tuna.tsinghua.edu.cn"
pypi = "https://mirrors.cernet.edu.cn/pypi"
rustup = "https://mirrors.cernet.edu.cn/rustup"
