import dataclasses
import enum
import functools
import hashlib
import re
import socket
from collections.abc import Container, Mapping, Sequence
from pathlib import Path

import tomllib

# /proc/sys/net/ipv4/ip_local_port_range
PORT_RANGE: Sequence[int] = range(32768, 60999)
# /etc/login.defs > UID_MIN..UID_MAX
UID_RANGE: Sequence[int] = range(10000, 60000)
# /etc/login.defs > GID_MIN..GID_MAX
GID_RANGE: Sequence[int] = range(10000, 60000)
NETWORK = tomllib.loads(
    (
        Path(__file__).resolve().parent.parent / "home/.chezmoidata/network.toml"
    ).read_text()
)["network"]
GATEWAY_HOSTS = {NETWORK["gateway_host"]}


class Field(enum.StrEnum):
    ENABLE = enum.auto()
    PORT = enum.auto()
    UID = enum.auto()


class Sentinel(enum.Enum):
    DISABLED = enum.auto()
    MISSING = enum.auto()


def digest(*parts: str) -> int:
    data: str = ":".join(parts)
    digest: bytes = hashlib.blake2b(data.encode()).digest()
    return int.from_bytes(digest)


@dataclasses.dataclass
class Service:
    name: str
    on: bool | Container[str] = True
    ports: Sequence[str] = ()
    fixed_ports: Mapping[str, int] = dataclasses.field(default_factory=dict)

    @functools.cached_property
    def enable(self) -> bool:
        if self.on is True:
            return True
        if self.on is False:
            return False
        return socket.gethostname() in self.on

    @functools.cached_property
    def slug(self) -> str:
        return re.sub(r"[- ]+", "_", self.name.lower())

    @functools.cached_property
    def uid(self) -> int | None:
        return UID_RANGE[digest(self.name, "uid") % len(UID_RANGE)]

    def print_properties(self) -> None:
        print(f"{self.slug}.enable = {'true' if self.enable else 'false'}")
        print(f"{self.slug}.uid = {self.uid}")
        for port_name in self.ports:
            port: int = (
                self.fixed_ports[port_name]
                if port_name in self.fixed_ports
                else PORT_RANGE[digest(self.name, port_name) % len(PORT_RANGE)]
            )
            print(f"{self.slug}.{port_name}.port = {port}")


SERVICES: list[Service] = [
    Service(
        "Caddy", on=GATEWAY_HOSTS, ports=("http", "https"), fixed_ports={"https": 443}
    ),
    Service("Cloudflared", on=GATEWAY_HOSTS if NETWORK["tunnel"]["enabled"] else False),
    Service("Dnsmasq", on=GATEWAY_HOSTS),
    Service("Forgejo", on={"PC07"}, ports=("http", "ssh")),
    Service("Jellyfin", on={"PC07"}, ports=("http",), fixed_ports={"http": 8096}),
    Service("Mihomo", on={"PC07"}, ports=("mixed",)),
    Service("OpenList", on={"PC07"}, ports=("http",), fixed_ports={"http": 5244}),
    Service("qBittorrent", on={"PC07"}, ports=("torrenting", "webui")),
    Service("Restic", on=True),
    Service("SSH", on=True, ports=("ssh",)),
]


def main() -> None:
    print("# This file is @generated by 'hooks/services.py'.")
    print("# DO NOT EDIT!")
    print("[services]")
    gid: int = GID_RANGE[digest("services", "gid") % len(GID_RANGE)]
    print(f"gid = {gid}")
    for s in SERVICES:
        s.print_properties()


if __name__ == "__main__":
    main()
