#!/bin/bash
# -*- mode: sh; -*-

source "$CHEZMOI_SOURCE_DIR/.snippets/has-nvidia.sh"

if has-nvidia; then
  # ref: <https://pot-app.com/en/docs/faq.html#nvidia-driver-issues-linux>
  echo 'WEBKIT_DISABLE_DMABUF_RENDERER=1'
fi
