[".config/latexindent/latexindent.yaml"]
type = "file"
url = "https://github.com/liblaf/ilatex/raw/main/.latexindent.yaml"

[".config/lf/colors"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/colors.example"

[".config/lf/icons"]
type = "file"
url = "https://github.com/gokcehan/lf/raw/master/etc/icons.example"

[".local/bin/color-make"]
executable = true
type = "file"
url = "https://github.com/liblaf/color-make/releases/latest/download/color-make-linux-amd64"

[".local/chezmoi/grub2-themes"]
stripComponents = 1
type = "archive"
url = "https://github.com/vinceliuice/grub2-themes/archive/refs/heads/master.tar.gz"

[".local/share/fonts/08_NotoSansCJKsc"]
exact = true
type = "archive"
url = "https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/08_NotoSansCJKsc.zip"

[".local/share/fonts/09_NotoSerifCJKsc"]
exact = true
type = "archive"
url = "https://github.com/notofonts/noto-cjk/releases/download/Serif2.001/09_NotoSerifCJKsc.zip"

[".local/share/fonts/13_NotoSansMonoCJKsc"]
exact = true
type = "archive"
url = "https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/13_NotoSansMonoCJKsc.zip"

[".local/share/fonts/FiraCode"]
exact = true
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip"

[".oh-my-zsh"]
stripComponents = 1
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/conda-zsh-completion"]
stripComponents = 1
type = "archive"
url = "https://github.com/conda-incubator/conda-zsh-completion/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
stripComponents = 1
type = "archive"
url = "https://github.com/marlonrichert/zsh-autocomplete/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-bitwarden"]
stripComponents = 1
type = "archive"
url = "https://github.com/Game4Move78/zsh-bitwarden/archive/refs/heads/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/heads/master.tar.gz"

["Desktop/github/liblaf/ddns"]
type = "git-repo"
url = "https://github.com/liblaf/ddns.git"

["Desktop/github/liblaf/ilatex"]
type = "git-repo"
url = "https://github.com/liblaf/ilatex.git"

["Desktop/github/other/gpt_academic"]
type = "git-repo"
url = "https://github.com/binary-husky/gpt_academic.git"
