# ref: <https://sw.kovidgoyal.net/kitty/conf/>

# ----------------------------------- Fonts ---------------------------------- #
font_family Maple Mono Normal NF CN
font_size 12.0

# ----------------------------------- Mouse ---------------------------------- #
copy_on_select yes
strip_trailing_spaces smart
## Mouse actions
mouse_map right click ungrabbed paste_from_clipboard

# ------------------------------- Window Layout ------------------------------ #
window_margin_width 6

# ---------------------------------- Tab bar --------------------------------- #
tab_bar_style powerline

# --------------------------------- Advanced --------------------------------- #
allow_remote_control yes
clipboard_control write-clipboard read-clipboard write-primary read-primary
notify_on_cmd_finish unfocused

# ---------------------------- Keyboard shortcuts ---------------------------- #
## Tab Management
map ctrl+shift+t new_tab_with_cwd
