defaultIndent: "  "

lookForAlignDelims:
  equation:
    delimiterRegEx: '(?<!\\)(&|\\qc)'
  equation*:
    delimiterRegEx: '(?<!\\)(&|\\qc)'
  gather:
    delimiterRegEx: '(?<!\\)(&|\\qc)'
  gather*:
    delimiterRegEx: '(?<!\\)(&|\\qc)'
  split:
    delimiterRegEx: '(?<!\\)(&|\\qc)'
