[".local/bin/fTetWild"]
executable = true
path = "bin/FloatTetwild_bin"
refreshPeriod = "168h"
type = "archive-file"
url = "https://github.com/chrismile/fTetWild/releases/latest/download/fTetWild-v0.1.0-x86_64-linux.zip"

[".local/bin/tangerine"]
executable = true
refreshPeriod = "168h"
type = "file"
url = "https://github.com/liblaf/tangerine/releases/latest/download/tangerine-x86_64-unknown-linux-gnu"

[".local/share/fish/vendor_completions.d/tangerine.fish"]
refreshPeriod = "168h"
type = "file"
url = "https://raw.githubusercontent.com/liblaf/tangerine/refs/heads/main/completions/fish/tangerine.fish"
