#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

function detect-intel() {
  if grep --ignore-case intel /proc/cpuinfo > /dev/null; then
    echo "hardware.intel.exists = true"
  else
    echo "hardware.intel.exists = false"
  fi
}

function detect-nvidia() {
  # ref: <https://wiki.archlinux.org/title/NVIDIA#Installation>
  data=$(lspci -vmm -d ::03xx)
  vendor=$(yq '.Vendor' <<< "$data")
  if [[ $vendor == 'NVIDIA Corporation' ]]; then
    echo 'hardware.nvidia.exists = true'
    device=$(yq '.Device' <<< "$data")
    codename=$(awk '{ print $1 }' <<< "$device")
    echo "hardware.nvidia.codename = \"$codename\""
    if grep --ignore-case mobile <<< "$device" > /dev/null; then
      echo 'hardware.nvidia.mobile = true'
    else
      echo 'hardware.nvidia.mobile = false'
    fi
  else
    echo 'hardware.nvidia.exists = false'
    echo 'hardware.nvidia.codename = ""'
    echo 'hardware.nvidia.mobile = false'
  fi
}

function detect-misc() {
  local chassis virt
  chassis="$(hostnamectl chassis)"
  virt="$(systemd-detect-virt || true)"
  echo "chassis = \"$chassis\""
  echo "virt = \"$virt\""
}

echo "# This file is @generated by 'scripts/gen-data/detect.sh'."
echo "# DO NOT EDIT!"
detect-intel
detect-nvidia
detect-misc
