import dataclasses
import enum
import functools
import hashlib
import re
import socket
from collections.abc import Container, Sequence

# /proc/sys/net/ipv4/ip_local_port_range
PORT_RANGE: Sequence[int] = range(32768, 60999)
# /etc/login.defs > UID_MIN..UID_MAX
UID_RANGE: Sequence[int] = range(10000, 60000)
# /etc/login.defs > GID_MIN..GID_MAX
GID_RANGE: Sequence[int] = range(10000, 60000)


class Field(enum.StrEnum):
    ENABLE = enum.auto()
    PORT = enum.auto()
    UID = enum.auto()


class Sentinel(enum.Enum):
    DISABLED = enum.auto()
    MISSING = enum.auto()


def digest(*parts: str) -> int:
    data: str = ":".join(parts)
    digest: bytes = hashlib.blake2b(data.encode()).digest()
    return int.from_bytes(digest)


@dataclasses.dataclass
class Service:
    name: str
    on: bool | Container[str] = True
    ports: Sequence[str] = ()

    @functools.cached_property
    def enable(self) -> bool:
        if self.on is True:
            return True
        if self.on is False:
            return False
        return socket.gethostname() in self.on

    @functools.cached_property
    def slug(self) -> str:
        return re.sub(r"[- ]+", "_", self.name.lower())

    @functools.cached_property
    def uid(self) -> int | None:
        return UID_RANGE[digest(self.name, "uid") % len(UID_RANGE)]

    def print_properties(self) -> None:
        print(f"{self.slug}.enable = {'true' if self.enable else 'false'}")
        print(f"{self.slug}.uid = {self.uid}")
        for port_name in self.ports:
            port: int = PORT_RANGE[digest(self.name, port_name) % len(PORT_RANGE)]
            print(f"{self.slug}.{port_name}.port = {port}")


SERVICES: list[Service] = [
    Service("Caddy", on=True, ports=("http", "https")),
    Service("Forgejo", on={"PC06"}, ports=("http", "ssh")),
    Service("Jellyfin", on={"PC06"}),
    Service("Mihomo", on={"PC06"}, ports=("mixed",)),
    Service("OpenList", on={"PC06"}),
    Service("qBittorrent", on={"PC06"}, ports=("torrenting", "webui")),
    Service("Restic", on=True),
    Service("SSH", on=True, ports=("ssh",)),
]


def main() -> None:
    print("# This file is @generated by 'scripts/gen-data/services.py'.")
    print("# DO NOT EDIT!")
    print("[services]")
    gid: int = GID_RANGE[digest("services", "gid") % len(GID_RANGE)]
    print(f"gid = {gid}")
    for s in SERVICES:
        s.print_properties()


if __name__ == "__main__":
    main()
