#:schema https://www.schemastore.org/tombi.json
# ref: <https://tombi-toml.github.io/tombi/docs/configuration>

[files]
include = ["**/*.toml", "**/*.toml.jinja", "**/*.toml.tmpl"]

[lsp]
completion.enabled = false  # enable until <https://github.com/tombi-toml/tombi/issues/716> is resolved

[schema]
strict = false
