# Configuration file for dnsmasq.
#
# Format is one option per line, legal options are the same
# as the long options legal on the command line. See
# "/usr/sbin/dnsmasq --help" or "man 8 dnsmasq" for details.

# ref: <https://dnsmasq.org/docs/dnsmasq-man.html>

no-hosts
interface=tailscale0
except-interface=lo
bind-dynamic
resolv-file=/run/NetworkManager/no-stub-resolv.conf
local=/pc07.tailf887c9.ts.net/

cname=forgejo.liblaf.me,pc07.tailf887c9.ts.net
cname=jellyfin.liblaf.me,pc07.tailf887c9.ts.net
cname=oplist.liblaf.me,pc07.tailf887c9.ts.net
cname=qbt.liblaf.me,pc07.tailf887c9.ts.net

interface-name=pc07.tailf887c9.ts.net,tailscale0
