name: Build

on:
  push:

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v2
      - name: Install Tools
        uses: liblaf/actions/install@main
        with:
          apt: stow
      - name: Build
        run: mise run build 'profiles/${{ matrix.profile }}.yaml'
      - name: Remove .gitignore
        run: rm --force '.gitignore'
      - if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "."
          branch: ${{ matrix.profile }}
          single-commit: true
    strategy:
      matrix:
        profile:
          - cachyos
