#:schema https://mise.jdx.dev/schema/mise.json

[env]
_.source = ".config/mise/scripts/env.sh"

[tasks.gen]
depends = ["gen-starship", "gen-ports"]

[tasks.gen-starship]
run = "python gen/starship/main.py"

[tasks.gen-ports]
run = "python gen/ports.py"
