[mirrors]
anaconda = "https://mirrors.cernet.edu.cn/anaconda"
anaconda_extra = "https://mirrors.cernet.edu.cn/anaconda-extra"
arch4edu = "https://mirrors.cernet.edu.cn/arch4edu/$arch"
archlinux = "https://mirrors.cernet.edu.cn/archlinux/$repo/os/$arch"
archlinuxcn = "https://mirrors.cernet.edu.cn/archlinuxcn/$arch"
bioarchlinux = "https://mirrors.cernet.edu.cn/bioarchlinux/$arch"
cachyos = "https://mirrors.ustc.edu.cn/cachyos"
crates_io_index = "sparse+https://mirrors.cernet.edu.cn/crates.io-index/"
dockerhub = "https://docker.m.daocloud.io"
flathub = "https://mirrors.cernet.edu.cn/flathub"
ghcr = "ghcr.nju.edu.cn"
go = "https://mirrors.huaweicloud.com/goproxy/"                           # CERNET 只有缓存
nodejs_release = "https://mirrors.cernet.edu.cn/nodejs-release"
npm = "https://mirrors.huaweicloud.com/repository/npm/"                   # CERNET 只有缓存
ntp = "ntp.tuna.tsinghua.edu.cn"
pypi = "https://mirrors.cernet.edu.cn/pypi/web/simple"
rustup = "https://mirrors.cernet.edu.cn/rustup"
